
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktuyzukgojkkiowillas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0dXl6dWtnb2pra2lvd2lsbGFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3NDI0NjUsImV4cCI6MjA1NDMxODQ2NX0.pRNJFKGIud9E-uGFddiYUKKcgiQinj8HLFhEKpizjxY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
